### ISSUE TITLE
Unable to run jupyterhub after adding nativeauthenticator as an authenticator class in the config file

### ISSUE THREAD

**Issue by shreeishitagupta** [jupyterhub/nativeauthenticator#126]
I followed the documentation and updated the config file after downloading the jupyterhub-authenticator but i am unable to start jupyterhub now. Getting this error:
''Bad config encountered during initialization: The 'authenticator_class' trait of <jupyterhub.app.JupyterHub object at 0x7f3c92dbf320> instance must be a type, but 'nativeauthenticator.NativeAuthenticator' could not be imported''

**Comment by lambdaTotoro** [comment]
Can you make sure you're running JupyterHub from the same python environment where you installed nativeAuthenticator (e.g. installing it as a normal user but running JupyterHub as superuser)?

Because if it can't be imported, that sounds like either something with the installation went wrong or this is an entirely different environment.
