### ISSUE TITLE
Test failure in main branch

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/nativeauthenticator#261]
Not yet investigated

**Comment by manics** [comment]
`pytest (3.8, jupyterhub==1.* sqlalchemy==1.*)` is currently failing https://github.com/jupyterhub/nativeauthenticator/actions/runs/10257308097/job/28378109882. All other matrix jobs including `pytest (3.9, jupyterhub==2.* sqlalchemy==1.*)` are passing.

Given that JupyterHub 1 is ancient and probably has several CVEs that are fixed in later versions I think we should drop it rather than trying to fix the failing test. Arguably we could drop JupyterHub 2, and maybe 3 too, to reduce the future maintenance burden

**Comment by consideRatio** [comment]
:+1: dropping support for jh <4
