### ISSUE TITLE
Project naming question

### ISSUE THREAD

**Issue by betatim** [jupyterhub/nativeauthenticator#66]
What is "native" about this authenticator? For me "native" and "first-class" are words we should avoid because they often imply a ranking "Native is better than not native" or "'first class X support' is better than 'we support X'". It reminds me discussions like "we need a kubernetes native multi user jupyter solution" which even when it isn't meant to confer a value judgement does often imply a judgement.

I hadn't given this much thought but did think of it when reading a draft blog post about the project.

**Comment by yuvipanda** [comment]
@betatim Native to me means 'Native to JupyterHub'. Do you or @leportella have suggested replacement names? 

I'd like us to set a deadline of say, 48h to publish the blog post, and go with Native if there isn't a better one.

**Comment by choldgraf** [comment]
my 2 cents: my naive interpretation of "native" was that this was an authenticator that is "built in" to JupyterHub (e.g., it doesn't use an outside service, and is more complex than something like a dummy authenticator). Is that correct? (just giving my perspective since that'll likely be the perspective of other folks new to the project)

**Comment by yuvipanda** [comment]
Yeah, that was my understanding when I set the name, @choldgraf.

**Comment by betatim** [comment]
The fact that it creates the impression that it is "built in" is what irks me (I think). Whether this authenticator is better/more expected/a better default than the PAM one is something we could discuss forever?

To me this package is a "batteries included" or "self contained" authenticator because everything is included and it has no external dependencies for user storage or user management. You install it and you are ready to go.

Some ideas off the top of my head: `AllInOneAuthenticator`, `SelfContainedAuthenticator`? Something riffing on batteries included :-/ I'll keep thinking.

**Comment by choldgraf** [comment]
I think @betatim raises a good point that we should be explicit about telling people which authenticators are "better", which should be used in which circumstances, etc. FWIW I don't really think that the word "native" make a strong signal for this (just my opinion though). 

How about we use this as an opportunity to improve the [authenticators page in z2jh](https://zero-to-jupyterhub.readthedocs.io/en/latest/authentication.html?highlight=authenticate) to give more helpful information about the relative differences, merits, etc of the authenticators?

**Comment by yuvipanda** [comment]
@betatim well, I *think* it should be built in to JupyterHub! This is what most people expect when they check out the 'built in' authentication mechanism of a web app - Wordpress, Mediawiki, GitLab, SquirrelMail, Joomla, Drupal, etc.

I agree with @choldgraf that the word 'Native' doesn't have any such strong signals. Once this authenticator gets more real world usage and depending on how many people use it, I'd love to actually get this inside core JupyterHub, and rename it appropriately then.

IMO, we shouldn't having a naming discussion *now*, while this has been what the project has been called for months since inception.

**Comment by betatim** [comment]
> IMO, we shouldn't having a naming discussion _now_, while this has been what the project has been called for months since inception.

When was there a discussion of this?

@yuvipanda well, I think "native" does imply a ranking.

---

I think this discussion has reached an unproductive level. I've voiced my thoughts to those who maintain this package so they can take them into account in their decisions.

**Comment by leportella** [comment]
As I understand [from the document that explains what this authenticator must have](https://github.com/jupyterhub/outreachy/blob/master/ideas/native-jupyterhub-user-management.rst), the idea was to built a "default" authenticator system that is more complex that some others (FirstUse and Dummy) and easier than the current default (PAM). Thus, for me it makes sense calling a "native" authenticator.

**Comment by consideRatio** [comment]
> I'd like us to set a deadline of say, 48h to publish the blog post, and go with Native if there isn't a better one.

48h hours has expired :) Closing!
