### ISSUE TITLE
Require users to confirm password in signup screen

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/nativeauthenticator#73]
We should have users type their password in twice during signup to make sure they are not making typos. Currently it's easy to make a typo and then be unable to log in.

**Comment by leportella** [comment]
[The text we used to base other password strength](https://auth0.com/blog/dont-pass-on-the-new-nist-password-guidelines/) characteristcs pointed out that being able to see the password is better then writing it twice, since allows you to create more complex things. That's why I didn't add a second one. You still think this is necessary?

**Comment by abbasidaniyal** [comment]
Hello
Is this issue still open / relative? 
I would like to work on it!

**Comment by harshu1470** [comment]
Can I work on it?

**Comment by lambdaTotoro** [comment]
Sure, make a pull request and we'll have a look.

**Comment by harshu1470** [comment]
Thanks @lambdaTotoro

**Comment by harshu1470** [comment]
why I am getting login page directly  instead of signup page after running jupyterhub?

**Comment by lambdaTotoro** [comment]
Defaulting to Login is a sensible thing to do, in my opinion, since logins are much, much more common than signups.

But please don't clog issues with unrelated questions.

**Comment by lambdaTotoro** [comment]
I actually think this is good to have. The text @leportella refers to speaks about making it possible for users to see their password on _login_, but it would also be nice to have them confirm it on _signup_ to root out typos in passwords.
